[local]
conn = "postgresql+psycopg://postgres@127.0.0.1:54322/postgres?sslmode=disable"

[staging]
conn = "postgresql+psycopg://postgres.zebzrvjbalhazztvhhcm@aws-1-us-west-1.pooler.supabase.com:6543/postgres?sslmode=require"
