SUPABASE_URL = "https://zebzrvjbalhazztvhhcm.supabase.co"
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplYnpydmpiYWxoYXp6dHZoaGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTM5OTgsImV4cCI6MjA3MjY4OTk5OH0.JNRpjAJ7yLaIh3Mvud7oLQoaofiGKGhaKqanc7AUR-0"
DB_URL = "postgresql://postgres@127.0.0.1:5432/postgres?sslmode=disable"
APP_URL = "http://localhost:8501/010_auth_login"
APP_LOCKED = false
