BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.digest(text, text)
RETURNS bytea
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $fn$
  SELECT digest(convert_to($1,'UTF8'), $2)
$fn$;

COMMIT;
