-- Fix v11_roi_flat_table_display: ensure tx_gt_* columns are never NULL/blank.
-- (Generated by ChatGPT)

CREATE OR REPLACE VIEW public.v11_roi_flat_table_display AS
WITH base AS (
  SELECT
    ps.experiment_date,
    ps.experiment_name,
    ps.plate_note,
    ps.slot_note,
    ps.slot_orientation,
    ra.roi_code,
    ra.roi_index_within_slot,
    ra.roi_note_anatomy,
    ra.roi_path,
    ps.clutch_code,
    m.treated_clutch_id,
    tg.treated_clutch_code,
    ps.treat_code AS treatment_code,
    ps.treat_text AS treatment_text,
    NULLIF(btrim(tg.treatment_label_tg_style), '') AS tg_style,
    NULLIF(btrim(tg.treatment_label_fluortag_style), '') AS ft_style,
    NULLIF(btrim(tg.treatment_label_fluororganelle_style), '') AS fo_style
  FROM imaging_roi_annotations ra
  LEFT JOIN v11_imaging_plate_slot_overview ps
    ON ps.slot_id::uuid = ra.slot_id
  LEFT JOIN imaging_clutch_memberships m
    ON m.slot_id = ra.slot_id
  LEFT JOIN v11_treated_clutch_genotype_star_labels tg
    ON tg.treated_clutch_id = m.treated_clutch_id
),
clean AS (
  SELECT
    base.experiment_date,
    base.experiment_name,
    base.plate_note,
    base.slot_note,
    base.slot_orientation,
    base.roi_code,
    base.roi_index_within_slot,
    base.roi_note_anatomy,
    base.roi_path,
    base.clutch_code,
    base.treated_clutch_id,
    base.treated_clutch_code,
    base.treatment_code,
    base.treatment_text,
    base.tg_style,
    base.ft_style,
    base.fo_style,
    NULLIF(btrim(regexp_replace(COALESCE(base.tg_style, ''), '^.*>[[:space:]]*', '')), '') AS tg_label,
    NULLIF(btrim(regexp_replace(COALESCE(base.ft_style, ''), '^[[:space:]]*>[[:space:]]*', '')), '') AS fluortag_label,
    NULLIF(btrim(regexp_replace(COALESCE(base.fo_style, ''), '^[[:space:]]*>[[:space:]]*', '')), '') AS fluororganelle_label_raw,
    (regexp_match(COALESCE(base.treatment_text, ''), '(?i)(?:^|\|)plasmids?=([^|]*)'))[1] AS plasmids_raw,
    (regexp_match(COALESCE(base.treatment_text, ''), '(?i)(?:^|\|)rnas?=([^|]*)'))[1] AS rnas_raw,
    (regexp_match(COALESCE(base.treatment_text, ''), '(?i)(?:^|\|)dyes?=([^|]*)'))[1] AS dyes_raw
  FROM base
),
fmt AS (
  SELECT
    clean.roi_path,
    clean.roi_note_anatomy,
    clean.slot_orientation,
    clean.plate_note,
    clean.slot_note,
    clean.experiment_name,
    clean.experiment_date,
    clean.roi_code,
    clean.roi_index_within_slot,
    clean.clutch_code,
    clean.treated_clutch_code,
    clean.treated_clutch_id,
    clean.treatment_code,
    clean.treatment_text,
    clean.tg_label,
    clean.fluortag_label,
    NULLIF(btrim(split_part(COALESCE(clean.fluororganelle_label_raw, ''), '>', 1)), '') AS fluororganelle_name,
    NULLIF(btrim(split_part(COALESCE(clean.fluororganelle_label_raw, ''), '>', 2)), '') AS fluororganelle_basecodes,
    NULLIF(btrim(clean.plasmids_raw), '') AS plasmids_basecodes,
    NULLIF(btrim(clean.rnas_raw), '') AS rnas_basecodes,
    NULLIF(btrim(clean.dyes_raw), '') AS dyes_codes,
    CASE
      WHEN NULLIF(btrim(clean.plasmids_raw), '') IS NULL THEN NULL
      ELSE ('plasmid(' || regexp_replace(btrim(clean.plasmids_raw), '\s*[;,]\s*|\s+', '), plasmid(', 'g')) || ')'
    END AS plasmids_display,
    CASE
      WHEN NULLIF(btrim(clean.rnas_raw), '') IS NULL THEN NULL
      ELSE ('rna(' || regexp_replace(btrim(clean.rnas_raw), '\s*[;,]\s*|\s+', '), rna(', 'g')) || ')'
    END AS rnas_display,
    CASE
      WHEN NULLIF(btrim(clean.dyes_raw), '') IS NULL THEN NULL
      ELSE ('dye(' || regexp_replace(btrim(clean.dyes_raw), '\s*[;,]\s*|\s+', '), dye(', 'g')) || ')'
    END AS dyes_display
  FROM clean
),
gx AS (
  SELECT c.clutch_code, c.genotype_v11_id
  FROM clutches c
),
tx AS (
  SELECT tc.treated_clutch_code, tc.treatment_id
  FROM treated_clutches_v11 tc
),
labels AS (
  SELECT
    f_1.roi_code,
    tls.treatment_display,
    gv.genotype_pretty,
    gls.fluor_tag_style AS gt_fluortag,
    gls.fluor_organelle_style AS gt_organelle,
    CASE
      WHEN NULLIF(btrim(COALESCE(tls.treatment_display, '')), '') IS NULL THEN NULLIF(btrim(COALESCE(gv.genotype_pretty, '')), '')
      WHEN NULLIF(btrim(COALESCE(gv.genotype_pretty, '')), '') IS NULL THEN tls.treatment_display
      ELSE (tls.treatment_display || ' > ') || gv.genotype_pretty
    END AS tx_gt_tg,
    CASE
      WHEN NULLIF(btrim(COALESCE(tls.fluor_tag_style, '')), '') IS NULL THEN NULL
      WHEN tls.treatment_display ILIKE 'rna(%' AND tls.treatment_display NOT ILIKE '%plasmid(%' THEN ('rna(' || tls.fluor_tag_style) || ')'
      WHEN tls.treatment_display ILIKE 'plasmid(%' AND tls.treatment_display NOT ILIKE '%rna(%' THEN ('plasmid(' || tls.fluor_tag_style) || ')'
      ELSE tls.fluor_tag_style
    END AS treat_fluortag_disp,
    CASE
      WHEN NULLIF(btrim(COALESCE(tls.fluor_organelle_style, '')), '') IS NULL THEN NULL
      WHEN tls.treatment_display ILIKE 'rna(%' AND tls.treatment_display NOT ILIKE '%plasmid(%' THEN ('rna(' || tls.fluor_organelle_style) || ')'
      WHEN tls.treatment_display ILIKE 'plasmid(%' AND tls.treatment_display NOT ILIKE '%rna(%' THEN ('plasmid(' || tls.fluor_organelle_style) || ')'
      ELSE tls.fluor_organelle_style
    END AS treat_organelle_disp
  FROM fmt f_1
  LEFT JOIN gx ON gx.clutch_code = f_1.clutch_code
  LEFT JOIN genotypes_v11 gv ON gv.id = gx.genotype_v11_id
  LEFT JOIN v11_genotype_label_star gls ON gls.genotype_v11_id = gx.genotype_v11_id
  LEFT JOIN tx ON tx.treated_clutch_code = f_1.treated_clutch_code
  LEFT JOIN v11_treatment_label_star tls ON tls.treatment_id::uuid = tx.treatment_id
)
SELECT
  f.*,
  COALESCE(l.tx_gt_tg, '') AS tx_gt_tg,
  COALESCE(
    CASE
      WHEN NULLIF(btrim(COALESCE(l.treat_fluortag_disp, '')), '') IS NULL THEN NULLIF(btrim(COALESCE(l.gt_fluortag, '')), '')
      WHEN NULLIF(btrim(COALESCE(l.gt_fluortag, '')), '') IS NULL THEN l.treat_fluortag_disp
      ELSE (l.treat_fluortag_disp || ' > ') || l.gt_fluortag
    END,
    ''
  ) AS tx_gt_fluortag,
  COALESCE(
    CASE
      WHEN NULLIF(btrim(COALESCE(l.treat_organelle_disp, '')), '') IS NULL THEN NULLIF(btrim(COALESCE(l.gt_organelle, '')), '')
      WHEN NULLIF(btrim(COALESCE(l.gt_organelle, '')), '') IS NULL THEN l.treat_organelle_disp
      ELSE (l.treat_organelle_disp || ' > ') || l.gt_organelle
    END,
    ''
  ) AS tx_gt_fluororganelle
FROM fmt f
LEFT JOIN labels l ON l.roi_code = f.roi_code;
