BEGIN;

-- Keep: uq_load_log_fish_batch_row (seed_batch_id, row_key)
-- Drop duplicate autogenerated name if it exists
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'load_log_fish_seed_batch_id_row_key_key'
      AND conrelid = 'public.load_log_fish'::regclass
  ) THEN
    ALTER TABLE public.load_log_fish
      DROP CONSTRAINT load_log_fish_seed_batch_id_row_key_key;
  END IF;
END$$;

COMMIT;
