[server]
# Don't watch virtualenvs or large dirs under the app tree
folderWatchBlacklist = [".venv", "supabase/ui/.venv", "node_modules", ".git"]
# Optional: if needed on macOS to reduce CPU
# fileWatcherType = "poll"
