# This file is setup to connect to a local supabase instance running from the host (e.g. supabase not running in the Dev Container).
# Copy the contents of this file to .streamlit\secrets.toml
# Run "supabase start" from the repo directory on the host.

CONN="postgresql://postgres:postgres@127.0.0.1:54322/postgres"

ENV="local"

APP_PASSWORD_SHA256="e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
# this will set the password to empty string

PGHOST="http://127.0.0.1:54322"
PGPORT=54322
PGPASSWORD="postgres"