# Copy to .streamlit/secrets.toml (do not commit that file)
ENV_NAME = "staging"
CONN = "postgresql+psycopg://<user>:<urlencoded_password>@aws-1-us-west-1.pooler.supabase.com:6543/postgres?sslmode=require"

# Or use PG* if your app assembles a DSN internally
PGHOST = "aws-1-us-west-1.pooler.supabase.com"
PGPORT = "6543"
PGUSER = "<user>"
PGPASSWORD = "<password>"
PGDATABASE = "postgres"
