# Sample (do NOT put real creds in git)
ENV_NAME = "staging"

# Option A: single DSN
# CONN = "postgresql+psycopg://USER:PASSWORD@HOST:PORT/DB?sslmode=require"

# Option B: parts
PGHOST = "aws-1-us-west-1.pooler.supabase.com"
PGPORT = "6543"
PGUSER = "postgres.zebzrvjbalhazztvhhcm"
PGPASSWORD = "<replace-in-cloud>"
PGDATABASE = "postgres"
