# Copy these into Streamlit Cloud -> App secrets (left panel) and fill real values.
DB_URL="postgresql://postgres:postgres@YOUR-PUBLIC-DB-HOST:5432/postgres?sslmode=require"
SUPABASE_URL="https://YOUR-REF.supabase.co"
SUPABASE_ANON_KEY="YOUR-ANON-KEY"

APP_ENV="prod"
APP_LOCKED=true
APP_PASSWORD_SHA256="YOUR-SHA256-PASSWORD-HASH"
