# Copy to .streamlit/secrets.toml for local dev
DB_URL = "postgresql://postgres@localhost:5432/postgres?sslmode=disable"
AUTH_MODE = "off"   # off | passcode | otp
STAGING_PROJECT_ID = "your-staging-project-id"
PROD_PROJECT_ID    = "your-prod-project-id"
# PASSCODE = "set-if-using-passcode"
